# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define :master do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.33.12"
    master.vm.network "public_network"
  end

  config.vm.define :slave1 do |slave1|
    slave1.vm.hostname = "slave1"
    slave1.vm.network "private_network", ip: "192.168.33.13"
    slave1.vm.network "public_network"
  end

  config.vm.define :slave2 do |slave2|
    slave2.vm.hostname = "slave2"
    slave2.vm.network "private_network", ip: "192.168.33.14"
    slave2.vm.network "public_network"
  end
end
